version: "3.9"
services:
  #aplicação web (PHP+NGINX)
  web:
    image: urnau/php-community:8.0.19-fpm-nginx
    # image: urnau/php-community:latest
    # utilizado quando vamos contruir uma nova imagem
    build: 
      context: .
      dockerfile: ./Dockerfile
    networks:
      - net_principal
    volumes:
      - ./applications:/var/www
      - ./docker/nginx/sites:/etc/nginx/sites-available
    ports:
      - "80:80" #http
      - "443:443" #https
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
      - "8089:8089"
    depends_on:
      - redis
      - mysql
  # aplicação MySQL
  mysql:
    image: mysql:8.0.29-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: g09huntf
      MYSQL_DATABASE: db_api-pagamentos
    networks:
      - net_principal
    ports:
      - 3306:3306
  # aplicação Redis
  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - net_principal
    ports:
      - 6379:6379

networks:
  net_principal:
